[tools]
bun = "latest"
node = "lts"

[hooks]
postinstall = "bun install && bun x playwright install --with-deps"

[vars]
entrypoint = "./src/index.ts"
build_args = '--outdir=dist --sourcemap --splitting --format=esm --target=browser --clean'

[tasks."build:esm"]
hide = true
run = "bun build {{vars.entrypoint}} {{vars.build_args}}"

[tasks."build:worklets"]
hide = true
run = "ls src/worklets/*.ts | xargs bun build {{vars.build_args}} --outdir=dist/worklets"

[tasks."build:min"]
hide = true
run = "bun build {{vars.entrypoint}} {{vars.build_args}} --minify --entry-naming=\"[dir]/[name].min.[ext]\""

[tasks."build:dts"]
hide = true
run = "bun x tsgo --project tsconfig.json"

[tasks.clean]
run = "rm -rf ./dist"

[tasks.fix]
run = "bun x biome check --fix"

[tasks.check]
run = "bun x biome check"

[tasks.build]
depends = ["clean"]
run = [{ tasks = ["build:esm", "build:worklets", "build:min", "build:dts"] }]

[tasks.test]
depends = ["build"]
run = "bun x playwright test"

[tasks."test:ui"]
depends = ["build"]
run = "bun x playwright test --ui"

[tasks."test:headed"]
depends = ["build"]
run = "bun x playwright test --headed"

[tasks."test:debug"]
depends = ["build"]
run = "bun x playwright test --debug"
