name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v4
      - name: Install dependencies
        run: pnpm install
      - name: Run lint
        run: pnpm biome check **/*.{cjs,ts}
      - name: Run tsc
        run: pnpm tsc
      - name: Run build
        run: pnpm build
