name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v3
      - name: Install dependencies
        run: pnpm install
      - name: Run lint
        run: pnpm biome check **/*.{cjs,ts}
      - name: Run tsc
        run: pnpm tsc
      - name: Run build
        run: pnpm build
