name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Setup mise-en-place
        uses: jdx/mise-action@v2
      - name: Install dependencies
        run: mise install && mise setup
      - name: Check code
        run: mise check
      - name: Run tests
        run: mise test        
